spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${local.database.url:jdbc:postgresql://localhost:5432/postgres}
    username: ${local.database.username:postgres}
    password: ${local.database.password:postgres}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
stock:
  companies: aapl, epam, msft, ibm
stocks:
  request:
    cache:
      size: 2